# Generated by Django 4.2.6 on 2023-11-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fufelnitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grymzik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shmurdik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sepulka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot', models.BooleanField()),
                ('soft', models.BooleanField()),
                ('square_or_small', models.TextField(choices=[('SQ', 'квадратная'), ('SM', 'маленькая')])),
                ('size', models.TextField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')])),
                ('state', models.TextField(choices=[('C', 'создана'), ('V', 'вакцинирована'), ('P', 'обработана напильником'), ('D', 'доставлена')])),
                ('datetime_created', models.DateField()),
                ('fufelnitsa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban_app.fufelnitsa')),
                ('grymzik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban_app.grymzik')),
                ('shmurdik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.shmurdik')),
            ],
        ),
    ]
