# Generated by Django 4.2.6 on 2023-11-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepulka',
            name='square_or_small',
            field=models.TextField(choices=[('square', 'квадратная'), ('small', 'маленькая')]),
        ),
        migrations.AlterField(
            model_name='sepulka',
            name='state',
            field=models.TextField(choices=[('C', 'создана'), ('V', 'вакцинирована'), ('P', 'обработана напильником'), ('D', 'доставлена')], default='C'),
        ),
    ]
