# Generated by Django 4.2.6 on 2023-11-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_alter_sepulka_fufelnitsa_alter_sepulka_grymzik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepulka',
            name='fufelnitsa',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepulka', to='kanban_app.fufelnitsa'),
        ),
        migrations.AlterField(
            model_name='sepulka',
            name='grymzik',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepulka', to='kanban_app.grymzik'),
        ),
        migrations.AlterField(
            model_name='sepulka',
            name='state',
            field=models.TextField(choices=[('C', 'создана'), ('V', 'вакцинируется'), ('P', 'обрабатывается напильником'), ('D', 'доставляется'), ('F', 'доставлена')], default='C'),
        ),
    ]
